# Generated by Django 5.0.4 on 2024-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='memberId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
