# Generated by Django 5.0.4 on 2024-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_id_member_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
